INHERIT: docs_template/mkdocs.yml

docs_dir: 'docs'

repo_name: Docker Bind
repo_url: https://github.com/nofusscomputing/docker-bind
edit_uri: '//edit/development/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Docker: 
  
    - projects/docker/index.md

    - Bind DNS Server:

      - projects/docker/bind/index.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

