INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Docker Bind
repo_url: https://gitlab.com/nofusscomputing/projects/docker-bind
edit_uri: '/-/ide/project/nofusscomputing/projects/docker-bind/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Docker: 
  
    - projects/docker/index.md

    - Bind DNS Server:

      - projects/docker/bind/index.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

