view "internal" {

    match-clients { internal_nets; };

    allow-recursion { internal_nets; };
    recursion yes;

    allow-query { internal_nets; };

    include "/etc/bind/conf.d/internal/*.zone.conf";

};