// Docs: https://bind9.readthedocs.io/en/v9.18.19/reference.html


include "/etc/bind/conf.d/logging.conf";
include "/etc/bind/conf.d/options.conf";
include "/etc/bind/conf.d/*.acl.conf";
include "/etc/bind/conf.d/internal.view.conf";
